version: "3"
services:
  ydb:
    image: cr.yandex/yc/yandex-docker-local-ydb:trunk
    environment:
      - "YDB_DEFAULT_LOG_LEVEL=DEBUG"
      - "GRPC_TLS_PORT=2135"
      - "GRPC_PORT=2136"
      - "MON_PORT=8765"
      - "YDB_USE_IN_MEMORY_PDISKS=true"
      - "POSTGRES_USER=${YDB_PG_USER:-postgres}"
      - "POSTGRES_PASSWORD=${YDB_PG_PASSWORD:-password}"
    healthcheck:
      test: "/bin/sh /health_check"
      interval: 1s
      start_period: 1m
  project:
    depends_on:
      ydb:
        condition: service_healthy
    image: ydb-test/go-pqlib
    build:
      context: .
    environment:
      - PGUSER=${YDB_PG_USER:-postgres}
      - PGPASSWORD=${YDB_PG_PASSWORD:-password}
      - PGHOST=${YDB_PG_HOST:-ydb}
      - PGPORT=${YDB_PG_PORT:-5432}
      - PGDATABASE=${YDB_PG_DATABASE:-/local}
      - PQGOSSLTESTS=0
      - PQSSLCERTTEST_PATH=certs
    volumes:
      - ./project-sources:/sources
      - ../../../tmp/test-result/go-libpq:/test-result
